### ekf config file ###
ekf_filter_node:
  ros__parameters:    #Configuation for robot odometry EKF
    use_sim_time: true
    frequency: 50.0
    two_d_mode: true

    odom0: /mecanum_drive_controller/odometry
    odom0_config: [false, false, false,
                  false, false, false,
                  true, true, false,
                  false, false, true,
                  false, false, false]
    odom0_differential: false
    imu0: /Dingo/imu
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_differential: false
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
