controller_manager:
  ros__parameters:
    update_rate: 50

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# mecanum_drive_controller:
#   ros__parameters:
#     fl_wheel_joint_name: front_left_wheel
#     fr_wheel_joint_name: front_right_wheel
#     rl_wheel_joint_name: rear_left_wheel
#     rr_wheel_joint_name: rear_right_wheel
#     wheel_radius: 0.05
#     wheel_distance:
#       width: 0.421
#       length: 0.57
mecanum_drive_controller:
  ros__parameters:
    reference_timeout: 0.1
    command_joint_names: ["front_left_wheel", "rear_left_wheel", "rear_right_wheel", "front_right_wheel"]
    interface_name: velocity
    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.991
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: false
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
